/**
 * ============================================================================
 *  CLIENT CONFIGURATION — the single place to edit business details.
 * ============================================================================
 *
 *  To reuse this website for another workshop:
 *    1. Edit the values in this file.
 *    2. Replace assets/source/logo-original.png and run `npm run assets`.
 *    3. Review service copy in src/data/services.ts and blog posts in src/data/blog.ts.
 *
 *  Anything marked `confirmed: false` (or listed in `pendingConfirmation`) is
 *  information the business owner still needs to verify. The site handles these
 *  gracefully: unconfirmed hours are not published in structured data, the
 *  emergency service stays hidden, and so on.
 * ============================================================================
 */

export type DayHours = { day: string; schemaDay: string; opens?: string; closes?: string; closed?: boolean };

export type Branch = {
  id: string;
  /** Short label, e.g. "Branch 1". */
  label: string;
  /** Landmark name used in headings, e.g. "Laiq Ali Chowk". */
  name: string;
  street: string;
  area: string;
  /** Map pin. When `confirmed` is false the map and directions search by address instead. */
  geo: { lat: number; lng: number; confirmed: boolean };
  /** Google Maps listing for this branch, if it has one. */
  mapsUrl: string;
};

/** Workshop locations. The first branch with a confirmed pin is used for the main map and schema. */
const branches: Branch[] = [
  {
    id: "laiq-ali-chowk",
    label: "Branch 1",
    name: "Laiq Ali Chowk",
    street: "Laiq Ali Chowk",
    area: "Wah Cantt",
    geo: { lat: 0, lng: 0, confirmed: false },
    mapsUrl: "",
  },
  {
    id: "new-city",
    label: "Branch 2",
    name: "New City Phase-1",
    street: "New City Phase-1, Main GT Road",
    area: "Wah Cantt",
    /** Pin from the Google Business Profile listing "My Mecahinc.pk (Branch-2)". */
    geo: { lat: 33.7549993, lng: 72.7558992, confirmed: true },
    mapsUrl: "https://maps.google.com/?cid=6405627770873787592",
  },
];

export const primaryBranch = branches.find((b) => b.geo.confirmed) ?? branches[0];

export const client = {
  /* ---------------------------------------------------------------- Identity */
  name: "My Mechanic.pk",
  legalName: "My Mechanic.pk",
  tagline: "Auto Workshop in Wah Cantt",
  description:
    "My Mechanic.pk is a car repair and maintenance workshop with two branches in Wah Cantt — Laiq Ali Chowk and New City Phase-1 on Main GT Road — offering computerized diagnostics, EFI and engine repair, AC servicing, brakes, suspension and routine maintenance for drivers across Wah Cantt and Taxila.",
  /** Year the business was established. Leave null until the owner confirms it. */
  foundingYear: null as number | null,

  /** Public site URL. NEXT_PUBLIC_SITE_URL overrides this at build time. */
  siteUrl: "https://www.mymechanic.pk",

  /* ------------------------------------------------------------------- Logo */
  logo: {
    /** Transparent logo (for dark backgrounds), generated by `npm run assets` from assets/source/logo-original.png */
    src: "/brand/logo.webp",
    /** Variant with dark lettering, shown in the light theme. Leave empty to use `src` in both themes. */
    srcLight: "/brand/logo-light.webp",
    fallbackPng: "/brand/logo.png",
    /** Intrinsic proportions of the generated logo — keep in sync to avoid distortion. */
    width: 640,
    height: 515,
    alt: "My Mechanic.pk Auto Workshop logo — a spanner across a gear above a steel plate with gold lettering",
  },

  /* ---------------------------------------------------------------- Contact */
  phone: {
    display: "0312-5045678",
    e164: "+923125045678",
  },
  whatsapp: {
    display: "0312-5045678",
    /** International format without "+" — used in https://wa.me/<number> */
    number: "923125045678",
  },
  /** Leave empty until the business provides a monitored email address. */
  email: "",

  branches,

  /** Primary address — Branch 2, which has the Google listing. Used for schema and single-address spots. */
  address: {
    street: "Main GT Road",
    area: "New City Phase-1",
    city: "Wah Cantt",
    region: "Punjab",
    postalCode: "47040",
    country: "Pakistan",
    countryCode: "PK",
  },

  /**
   * Map coordinates of the primary branch. When `confirmed` is false the
   * coordinates are NOT published in structured data and the map uses the address search.
   */
  geo: primaryBranch.geo,

  /** Google Business Profile (Maps listing, by cid). */
  googleBusinessProfileUrl: primaryBranch.mapsUrl,
  /**
   * "Leave a review" link. Points at the Maps listing (which has a Write a review button);
   * swap in the direct search.google.com/local/writereview?placeid=… link when available.
   */
  googleReviewUrl: primaryBranch.mapsUrl,

  /* ------------------------------------------------------------------ Hours */
  hours: {
    /** Set to true only after the owner confirms these times. */
    confirmed: false,
    note: "Please call or WhatsApp before visiting — opening hours are being confirmed.",
    days: [
      { day: "Monday", schemaDay: "Monday" },
      { day: "Tuesday", schemaDay: "Tuesday" },
      { day: "Wednesday", schemaDay: "Wednesday" },
      { day: "Thursday", schemaDay: "Thursday" },
      { day: "Friday", schemaDay: "Friday" },
      { day: "Saturday", schemaDay: "Saturday" },
      { day: "Sunday", schemaDay: "Sunday" },
    ] as DayHours[],
  },

  /* ------------------------------------------------------------------ Social */
  social: {
    handle: "@mymechanic.pk",
    links: [
      { label: "Facebook", href: "https://www.facebook.com/p/My-MechanicPk-100083210360615/" },
      { label: "Instagram", href: "https://www.instagram.com/mymechanic.pk/" },
    ],
  },

  /* ------------------------------------------------------------ Service area */
  serviceAreas: {
    primary: ["Wah Cantt", "Taxila"],
    /** Nearby localities mentioned in copy. Keep to areas the workshop genuinely serves. */
    nearby: ["Laiq Ali Chowk", "New City Phase-1 & 2", "Main GT Road", "Wah Model Town", "Hasan Abdal", "Sangjani"],
  },

  /* ------------------------------------------------------------ Brand colors */
  /** Mirrors the CSS tokens in src/app/globals.css (@theme). Used for manifest/meta. */
  colors: {
    brand: "#f5b301",
    brandDeep: "#c48a00",
    background: "#0c0d0f",
    surface: "#17191d",
    metal: "#9ba1a9",
  },

  /* -------------------------------------------------------------------- SEO */
  seo: {
    /** Google Search Console HTML-tag verification token (content of google-site-verification). */
    googleSiteVerification: "",
    defaultTitle: "My Mechanic.pk | Car Repair Workshop in Wah Cantt",
    titleTemplate: "%s | My Mechanic.pk",
    defaultDescription:
      "Car repair and maintenance in Wah Cantt with two branches — Laiq Ali Chowk and New City Phase-1, GT Road. Computerized scanning, EFI, engine, AC, brakes and suspension.",
    keywords: [
      "car mechanic Wah Cantt",
      "car repair workshop Wah Cantt",
      "auto workshop New City Wah",
      "car mechanic Laiq Ali Chowk",
      "car computerized scanning Wah Cantt",
      "car repair Taxila",
      "car AC repair Wah Cantt",
    ],
    ogImage: "/brand/og-image.jpg",
    locale: "en_PK",
    twitterHandle: "",
  },

  /* ---------------------------------------------------------------- Privacy */
  analytics: {
    /**
     * Google Analytics 4 measurement ID (e.g. "G-XXXXXXX"). Leave empty to load no
     * analytics at all — in that case no cookie banner is shown because the site
     * sets no non-essential cookies.
     */
    ga4Id: "",
  },

  /** Last date the legal pages were reviewed. */
  legalUpdated: "2026-09-30",
} as const;

/**
 * Things the business owner still needs to confirm or supply.
 * Surfaced in CLIENT-CHECKLIST.md — keep the two in sync.
 */
export const pendingConfirmation = [
  "WhatsApp number (currently assumed to be the same as the phone, 0312-5045678)",
  "Opening hours for each branch (client.hours)",
  "Full street address and map pin for Branch 1, Laiq Ali Chowk (client.branches)",
  "Services actually offered and any specialist equipment (src/data/services.ts)",
  "Business email address (client.email)",
  "Year established (client.foundingYear)",
  "Direct Google \"write a review\" link (client.googleReviewUrl currently opens the Maps listing)",
  "Whether emergency breakdown assistance is offered (services.ts → emergency-breakdown-assistance)",
  "Workshop photographs and videos of both branches",
  "Technician names, qualifications and experience (About page)",
  "Final domain name (client.siteUrl)",
] as const;

export const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || client.siteUrl).replace(/\/$/, "");

export const branchAddress = (b: Branch) => [b.street, b.area].filter(Boolean).join(", ");

export const fullAddress = [client.address.street, client.address.area, client.address.city, client.address.country]
  .filter(Boolean)
  .join(", ");
